name: Package Release
on:
  push:
    branches:
      - "releases/**"
  workflow_dispatch:

jobs:
  package-release:
    strategy:
      matrix:
        os: [windows-latest, macos-14]
        python_version: ['3.10', '3.11']
        include:
          - os: windows-latest
            requirements: win-linux-cuda.txt
            filename: windows-cuda
          - os: windows-latest
            requirements: win-dml.txt
            filename: windows-directml
          - os: macos-latest
            requirements: mac-mps-cpu.txt
            filename: macos-arm
          - python_version: '3.11'
            filename_suffix: '-4-1'
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          path: dream_textures
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python_version }}
          cache: 'pip'
          cache-dependency-path: '**/${{ matrix.requirements }}'
      - name: Install dependencies into target
        shell: bash
        run: 'python -m pip install -r requirements/${{ matrix.requirements }} --no-cache-dir --target .python_dependencies'
        working-directory: dream_textures
      - name: Zip dependencies with long paths
        shell: bash
        run: 'python ./dream_textures/scripts/zip_dependencies.py'
      - name: Archive Release
        uses: thedoctor0/zip-release@main
        with:
          type: zip
          filename: dream_textures-${{ matrix.filename }}${{ matrix.filename_suffix }}.zip
          exclusions: '*.git*'
      - name: Archive and upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: dream_textures-${{ matrix.filename }}${{ matrix.filename_suffix }}
          path: dream_textures-${{ matrix.filename }}${{ matrix.filename_suffix }}.zip